Repository kubermatic/kubevirt-csi-driver-operator, pull requests merged in 2024-10, with the labels that each got.

#21 Support VolumeModeBinding in Tenant StorageClass
  api/v1alpha1/tenant_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/csiprovisioner.kubevirt.io_tenants.yaml
  controllers/tenant/storageclass.go
  go.mod
  go.sum
Labels: sig/cluster-management, release-note, approved, lgtm, dco-signoff: yes, size/S

#22 Introduce a new field in the Tenant.Spec.StorageClasses CRD(Labels)
  api/v1alpha1/tenant_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/csiprovisioner.kubevirt.io_tenants.yaml
  controllers/tenant/storageclass.go
Labels: sig/cluster-management, release-note, approved, lgtm, dco-signoff: yes, size/S

#20 Updated the daemonset image to upstream
  controllers/tenant/daemonset.go
Labels: sig/cluster-management, release-note, approved, lgtm, dco-signoff: yes, size/XS

#23 Support allowed topologies
  api/v1alpha1/tenant_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/csiprovisioner.kubevirt.io_tenants.yaml
  controllers/tenant/storageclass.go
Labels: sig/cluster-management, size/M, approved, lgtm, dco-signoff: yes
